### ISSUE TITLE
Causes shutdown/restart/sleep/hibernate/logout dialogues all to stack onto one monitor

### ISSUE THREAD

**Issue by CTalvio** [nclarius/KWin-window-positioning-scripts#13]
KDE opens a fullscreen windows for each monitor when selecting shutdown/restart/sleep/hibernate/logout. When the script is active, these all get stacked onto one monitor. This looks especially weird when your monitor resolutions differ.

Obviously the script is causing them to open on the active monitor, but this is a specific case where that behaviour is really never desired.

**Comment by nclarius** [comment]
This exact issue should have been fixed with the most recent version.

Which of the scripts and which version are you using?

And X11 or Wayland?

**Comment by CTalvio** [comment]
Ah, seems 3.0 is not yet on the KDE store. I was on 2.8. Active monitor script, X11.

I installed 3.0 from here and now it no longer happens. My bad, thanks!

**Comment by nclarius** [comment]
I did upload v3.0 to the store and can see it in the install dialog, but the way KNewStuff displays the versions is somewhat messy so it's easy to miss. Anyway, glad it works for you now.
