### ISSUE TITLE
Discover installs outdated version of script

### ISSUE THREAD

**Issue by zany130** [nclarius/KWin-window-positioning-scripts#16]
just installing the script does not add the configuration button so I tried running this (which the readme says should no longer be needed on 5.24?)
```
sed -i 's/ConfigModule/Library/g' ~/.local/share/kwin/scripts/alwaysopenonprimaryscreen/metadata.desktop
mkdir -p ~/.local/share/kservices5/
ln -sf ~/.local/share/kwin/scripts/alwaysopenonprimaryscreen/metadata.desktop ~/.local/share/kservices5/alwaysopenonprimaryscreen.desktop
qdbus org.kde.KWin /KWin reconfigure
```
 and I get this error
 ![image](https://user-images.githubusercontent.com/25832539/167270160-e205d998-5f87-40ca-902c-f6f35342a0e6.png)

```
inxi -b
System:
  Host: Kiseki Kernel: 5.17.5-256-tkg-pds arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Garuda Linux
Machine:
  Type: Desktop Mobo: ASRock model: X470 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P4.86 date: 01/27/2022
CPU:
  Info: 6-core AMD Ryzen 5 2600X [MT MCP] speed (MHz): avg: 4132
    min/max: 2200/3600
Graphics:
  Device-1: NVIDIA GP104 [GeForce GTX 1080] driver: nvidia v: 510.68.02
  Display: x11 server: X.Org v: 21.1.3 with: Xwayland v: 22.1.1 driver: X:
    loaded: nvidia gpu: nvidia,nvidia-nvswitch resolution: 1: 2560x1080
    2: 3840x2160~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1080/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.68.02
Network:
  Device-1: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 2.96 TiB used: 2.97 TiB (100.4%)
Info:
  Processes: 462 Uptime: 2h 33m Memory: 31.27 GiB used: 19.92 GiB (63.7%)
  Shell: fish inxi: 3.3.15
  ```

**Comment by nclarius** [comment]
Are you sure you have the up to date version of the script (v4.0) installed?

**Comment by zany130** [comment]
I have the version that's available in the discover app store which checking the version info says 4.0, released on 5/3/22

**Comment by nclarius** [comment]
I just tried it out on my test user account and Discover for whatever reason decided to install version v2.1 instead. That's bad, I'll file a bug report about it (edit: [here it is](https://bugs.kde.org/show_bug.cgi?id=453521)); thanks for making me aware of it.  
You can verify the version number by clicking the info button which is next to the configuration button.
If you ended up with the wrong version, please uninstall it and install the script again through the "Get New Scripts..." button at the bottom of the settings page, this will let you select the correct version.

**Comment by nclarius** [comment]
Closing as there is not much to be discussed here; this bug needs to get fixed in Discover.
