### ISSUE TITLE
Steam not ignored (Always Open on Active Screen)

### ISSUE THREAD

**Issue by zany130** [nclarius/KWin-window-positioning-scripts#19]
I have a kwin rule to open steam initially on my tv

Therefore I added steam to the ignore list so it does not conflict, however, it keeps forcing it on my active window (which I don't want)

I tried several different values to ignore steam including 
```
steam-runtime
steam
steam-native
Steam
steam steam
```
and steam is always opened on the active screen.

If I disable the script steam opens on my tv as expected

**Comment by nclarius** [comment]
Please verify if the new version solves the issue.

**Comment by zany130** [comment]
works just fine now on the latest version with 
`steam steam` (which is the full window class name for steam) into the ignore list
