### ISSUE TITLE
Always on Primary Screen doesnt work

### ISSUE THREAD

**Issue by Dyadya-Sasha** [nclarius/KWin-window-positioning-scripts#20]
Hello all,
I have installed Always on Primary Screen and it doesnt work as it should. 
I use Arch and the latest KDE. Checkbox "Primary" set in Display settings. I have tried to apply and reapply the script but no result.
What can I do to make it work? I am ready to provide all the info you need but dont really know what exactly.

```
Operating System: Arch Linux
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5
Kernel Version: 5.19.6-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-1035G1 CPU @ 1.00GHz
Memory: 7.6 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: HP
Product Name: HP 250 G8 Notebook PC
System Version: Type1ProductConfigId
```

UPDATE:  I disabled "Window Management->Advanced->Allow apps to remember the positions of their own window", but it works not on every app. For example Google Chrome still gets opened on second display for some reason

**Comment by nclarius** [comment]
Thanks for the report. The recent update (v5.0) should have resolved this. If not, please reopen the issue.
