### ISSUE TITLE
Unclear which version to install

### ISSUE THREAD

**Issue by felagund** [nclarius/KWin-window-positioning-scripts#21]
When installing the script trough system settings, ti lets me pick from many versions. I assume the correct one is the one on the top but I have no idea, really. It tells me to contact the authors, so I am doing that.
![Screenshot_20220921_101423](https://user-images.githubusercontent.com/1218098/191452147-04590a16-694b-440a-9596-346a10950258.png)

**Comment by nclarius** [comment]
The current version is ..._v4.0 (second entry). 

Sorry for the messy presentation. You can get a clean overview with version number labels in the [browser interface](https://store.kde.org/p/1618008) (tab Files), but I realized too late that the KDE integrated downloader doesn't show them, and can't change the old versions now.

**Comment by felagund** [comment]
I see. It is weird to me that the old versions are even still there, but I guess it is a defifciency of the downloader...
