### ISSUE TITLE
Scripts seem to not work on 5.24.6

### ISSUE THREAD

**Issue by levis-apps** [nclarius/KWin-window-positioning-scripts#22]
Hey,
I really loved your "Always Open on Active Screen" script and used it all the time.
Istead of upgrading from ubuntu 21.10 to 22.04 I chose a clean install of kubuntu.
Now none of those scripts work (others do) and with default window behaviour settings. Iv'e tried literally everything.

```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-48-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-7200U CPU @ 2.50GHz
Memory: 7.1 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 620
```

Thanks

Edit:
The probelm is solved when I use an older version of the script (v3.0).

**Comment by jimbobjonesbob** [comment]
yes, didn't work for me in 5.24.6 either

**Comment by Slothinger** [comment]
Same prob with v4, but v3 works.

**Comment by nclarius** [comment]
Should be fixed now.
