### ISSUE TITLE
Script spams logs with debug info

### ISSUE THREAD

**Issue by aginiewicz** [nclarius/KWin-window-positioning-scripts#23]
Since 70069b5e893592f27ba5f3920bca644ced969903 option for disabling debug info is not visible in options of always-open-on-primary-screen, and debug is enabled by default. This causes plenty of debug info (which is huge for this script as it includes json for window object) to spam logs and makes looking trough journalctl extremely hard. Is this intended behaviour?

**Comment by nclarius** [comment]
You can do

```
kwriteconfig5 --file kwinrc --group Script-alwaysopenonprimaryscreen --key debugMode false
qdbus org.kde.KWin /KWin reconfigure
```
