### ISSUE TITLE
KDE store install and download broken

### ISSUE THREAD

**Issue by noyannus** [nclarius/KWin-window-positioning-scripts#24]
Attempt to download or install from KDE store fail.
```
failurefilemtime(): stat failed for /mnt/s3/files/data/files/1634390554/always-open-on-focused-screen-v5.0.kwinscript
```
Assuming `s3` in the path means Amazon S3, if data there are corrupted it's possible that you will have to recreate the data on that account.

**Comment by nclarius** [comment]
How did you download it exactly? From the web browser on store.kde.org?  

Not sure what the error means but the store has nothing to do with Amazon

**Comment by noyannus** [comment]
I used `Firefox 113.0 (64-bit) Linux`on `https://store.kde.org/p/1618008`. Tried both top right buttons `Download` and `Install` for `always-open-on-focused-screen-v5.0.kwinscript`.

On the appearing overlays I clicked their respective blue buttons, after the download/install was "ready". 

`Download` returned the page 
```
https://files03.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTY2OTIxNDI5OSwidSI6bnVsbCwibHQiOiJkb3dubG9hZCIsInMiOiJhYmZlOTkxZTZmNzlmMTY5OTAyMDExNzdiM2FlYTgzMjVmYmJmM2U4MDJkMWQ5NDNkMWYwNDdkNzM0ZTEzOGNkNjBjYTA1ZWI1ZTlkNzI1ZjllYWNlZTc3NGNkNTk0ZDQ3YThiNGE0MDU5MzdmNTJjZDI2NzhiOTJkYTExZTE4NCIsInQiOjE2ODM4OTU1NzgsInN0ZnAiOiIzZWI0NWQ1MzQ5ZDYzNDQ4ODk2NzdkNWEyZWQ3NjBlMyIsInN0aXAiOiIyMDAxOjllODo0MzY4OjhkMDA6MTg3YzplNmNiOjViZTQ6OWE2MSJ9.xIEEXiuF3O-0AyOzFqnRKhj4hZcHqF25_f_tXrVzXtQ/always-open-on-focused-screen-v5.0.kwinscript
```
that displayed only this
```
errorfile not found (id: ZF4z7_qOKbWLMK50Xpk9MwAAV)
```
or alternatively the page
```
https://files03.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTY2OTIxNDI5OSwidSI6bnVsbCwibHQiOiJkb3dubG9hZCIsInMiOiJhYmZlOTkxZTZmNzlmMTY5OTAyMDExNzdiM2FlYTgzMjVmYmJmM2U4MDJkMWQ5NDNkMWYwNDdkNzM0ZTEzOGNkNjBjYTA1ZWI1ZTlkNzI1ZjllYWNlZTc3NGNkNTk0ZDQ3YThiNGE0MDU5MzdmNTJjZDI2NzhiOTJkYTExZTE4NCIsInQiOjE2ODM4OTU1NzgsInN0ZnAiOiIzZWI0NWQ1MzQ5ZDYzNDQ4ODk2NzdkNWEyZWQ3NjBlMyIsInN0aXAiOiIyMDAxOjllODo0MzY4OjhkMDA6MTg3YzplNmNiOjViZTQ6OWE2MSJ9.xIEEXiuF3O-0AyOzFqnRKhj4hZcHqF25_f_tXrVzXtQ/always-open-on-focused-screen-v5.0.kwinscript
```
that stated:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<status>error</status>
<message>file not found (id: ZF4zQpzh5TuAu37FhbAe1AAAj)</message>
</response>
````

Clicking `Install` on the overlay,
a dialog asked if I wanted to install, after confirmation an error popped up:

![2023-05-12_14-05-26](https://github.com/nclarius/KWin-window-positioning-scripts/assets/6339921/652c9e56-1f69-452a-90b8-ac9097be48b2)


Re Amazon, that was only a suspicion in case the store data were outsourced.

**Comment by nclarius** [comment]
I forwarded it to the maintainers of the KDE store and they said it should be fixed now; please try again.

**Comment by noyannus** [comment]
Both work on Chromium and Firefox now. 
Thanks (also to the KDE folks!).

Have a fine weekend!
