### ISSUE TITLE
Step Re-Grid: Feature request: Resize with the mouse?

### ISSUE THREAD

**Issue by jlemonde** [nclarius/KWin-window-positioning-scripts#3]
Dear nclarius,
I really like your new kwin script! 

I only feel that I can't find any useful keybindings that aren't already taken by my setup or by specific apps (especially those with Alt are heavily used within apps). So I wanted to know whether it would be possible to run this script based on mouse resizes. That would be a nice feature!

Thank you for considering this,
I can understand if this isn't your priority, but it may make it even more popular!

**Comment by nclarius** [comment]
The purpose of this script is specifically to make resizing keyboard-accessible. For adjusting neighboring windows when the active window is resized with the mouse, there already are the very nice [Sticky Window Snapping](https://www.pling.com/p/1112552) and [KWin Quick Tile Enhancements](https://www.pling.com/find?search=quick%20tile%20enhancements) scripts.

**Comment by nclarius** [comment]
(If you haven't already, you could of course also consider key combinations with multiple modifiers, such as Meta+Alt+something.)

**Comment by jlemonde** [comment]
Thanks for your answer. But well, neither of the two scripts you suggest works with "Tile Gaps". "Step Re-Grid" is the only extension that I know of which is compatible with "Tile Gaps", this is why I was asking.

**Comment by nclarius** [comment]
See the readme of Tile Gaps: I made a [fork of sticky window snapping](https://github.com/nclarius/tile-gaps) that is compatible with tile gaps. I already filed a pull request to merge these changes into the official version of sticky window snapping, but it is up to the author to decide to adopt these changes; until then my fork should work well enough.
