### ISSUE TITLE
Script request

### ISSUE THREAD

**Issue by gobonja** [nclarius/KWin-window-positioning-scripts#4]
First of all great job with current scripts! :)

I was wondering if you could create script that does same thing as [Virtual Desktops Only On Primary](https://store.kde.org/p/1398114)

This one is no longer maintained and has some bugs and I found this feature useful.

Best regards

**Comment by nclarius** [comment]
Thanks for the suggestion. I can look into it at some point, but it won't be high priority as I don't have any use for it myself.
